/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyResultsRouteImport } from './routes/survey-results'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembersRouteImport } from './routes/members'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MembersSlugRouteImport } from './routes/members_.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiMemberMediaAssetIdRouteImport } from './routes/api.member-media.$assetId'

const SurveyResultsRoute = SurveyResultsRouteImport.update({
  id: '/survey-results',
  path: '/survey-results',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MembersSlugRoute = MembersSlugRouteImport.update({
  id: '/members_/$slug',
  path: '/members/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemberMediaAssetIdRoute = ApiMemberMediaAssetIdRouteImport.update({
  id: '/api/member-media/$assetId',
  path: '/api/member-media/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/survey': typeof SurveyRoute
  '/survey-results': typeof SurveyResultsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/members/$slug': typeof MembersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/member-media/$assetId': typeof ApiMemberMediaAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/survey': typeof SurveyRoute
  '/survey-results': typeof SurveyResultsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/members/$slug': typeof MembersSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/member-media/$assetId': typeof ApiMemberMediaAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/survey': typeof SurveyRoute
  '/survey-results': typeof SurveyResultsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/members_/$slug': typeof MembersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/member-media/$assetId': typeof ApiMemberMediaAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/events'
    | '/members'
    | '/news'
    | '/survey'
    | '/survey-results'
    | '/auth/callback'
    | '/members/$slug'
    | '/admin/'
    | '/api/member-media/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/members'
    | '/news'
    | '/survey'
    | '/survey-results'
    | '/auth/callback'
    | '/members/$slug'
    | '/admin'
    | '/api/member-media/$assetId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/events'
    | '/members'
    | '/news'
    | '/survey'
    | '/survey-results'
    | '/auth/callback'
    | '/members_/$slug'
    | '/admin/'
    | '/api/member-media/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  MembersRoute: typeof MembersRoute
  NewsRoute: typeof NewsRoute
  SurveyRoute: typeof SurveyRoute
  SurveyResultsRoute: typeof SurveyResultsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MembersSlugRoute: typeof MembersSlugRoute
  ApiMemberMediaAssetIdRoute: typeof ApiMemberMediaAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survey-results': {
      id: '/survey-results'
      path: '/survey-results'
      fullPath: '/survey-results'
      preLoaderRoute: typeof SurveyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/members_/$slug': {
      id: '/members_/$slug'
      path: '/members/$slug'
      fullPath: '/members/$slug'
      preLoaderRoute: typeof MembersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/member-media/$assetId': {
      id: '/api/member-media/$assetId'
      path: '/api/member-media/$assetId'
      fullPath: '/api/member-media/$assetId'
      preLoaderRoute: typeof ApiMemberMediaAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  MembersRoute: MembersRoute,
  NewsRoute: NewsRoute,
  SurveyRoute: SurveyRoute,
  SurveyResultsRoute: SurveyResultsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MembersSlugRoute: MembersSlugRoute,
  ApiMemberMediaAssetIdRoute: ApiMemberMediaAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
