/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyResultsRouteImport } from './routes/survey-results'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembersRouteImport } from './routes/members'
import { Route as GuildRouteImport } from './routes/guild'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuildIndexRouteImport } from './routes/guild.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SendTokenRouteImport } from './routes/send.$token'
import { Route as MembersSlugRouteImport } from './routes/members_.$slug'
import { Route as GuildRosterRouteImport } from './routes/guild.roster'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminHoursRouteImport } from './routes/admin.hours'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDiscountRouteImport } from './routes/admin.discount'
import { Route as AdminBasicsRouteImport } from './routes/admin.basics'
import { Route as ApiMemberMediaAssetIdRouteImport } from './routes/api.member-media.$assetId'
import { Route as ApiConfirmHoursTokenRouteImport } from './routes/api.confirm-hours.$token'
import { Route as ApiAdminMediaAssetIdRouteImport } from './routes/api.admin-media.$assetId'

const SurveyResultsRoute = SurveyResultsRouteImport.update({
  id: '/survey-results',
  path: '/survey-results',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildRoute = GuildRouteImport.update({
  id: '/guild',
  path: '/guild',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildIndexRoute = GuildIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuildRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SendTokenRoute = SendTokenRouteImport.update({
  id: '/send/$token',
  path: '/send/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersSlugRoute = MembersSlugRouteImport.update({
  id: '/members_/$slug',
  path: '/members/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildRosterRoute = GuildRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => GuildRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoursRoute = AdminHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountRoute = AdminDiscountRouteImport.update({
  id: '/discount',
  path: '/discount',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBasicsRoute = AdminBasicsRouteImport.update({
  id: '/basics',
  path: '/basics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiMemberMediaAssetIdRoute = ApiMemberMediaAssetIdRouteImport.update({
  id: '/api/member-media/$assetId',
  path: '/api/member-media/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfirmHoursTokenRoute = ApiConfirmHoursTokenRouteImport.update({
  id: '/api/confirm-hours/$token',
  path: '/api/confirm-hours/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaAssetIdRoute = ApiAdminMediaAssetIdRouteImport.update({
  id: '/api/admin-media/$assetId',
  path: '/api/admin-media/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/guild': typeof GuildRouteWithChildren
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/signin': typeof SigninRoute
  '/survey': typeof SurveyRoute
  '/survey-results': typeof SurveyResultsRoute
  '/admin/basics': typeof AdminBasicsRoute
  '/admin/discount': typeof AdminDiscountRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/theme': typeof AdminThemeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guild/roster': typeof GuildRosterRoute
  '/members/$slug': typeof MembersSlugRoute
  '/send/$token': typeof SendTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/guild/': typeof GuildIndexRoute
  '/api/admin-media/$assetId': typeof ApiAdminMediaAssetIdRoute
  '/api/confirm-hours/$token': typeof ApiConfirmHoursTokenRoute
  '/api/member-media/$assetId': typeof ApiMemberMediaAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/signin': typeof SigninRoute
  '/survey': typeof SurveyRoute
  '/survey-results': typeof SurveyResultsRoute
  '/admin/basics': typeof AdminBasicsRoute
  '/admin/discount': typeof AdminDiscountRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/theme': typeof AdminThemeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guild/roster': typeof GuildRosterRoute
  '/members/$slug': typeof MembersSlugRoute
  '/send/$token': typeof SendTokenRoute
  '/admin': typeof AdminIndexRoute
  '/guild': typeof GuildIndexRoute
  '/api/admin-media/$assetId': typeof ApiAdminMediaAssetIdRoute
  '/api/confirm-hours/$token': typeof ApiConfirmHoursTokenRoute
  '/api/member-media/$assetId': typeof ApiMemberMediaAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/guild': typeof GuildRouteWithChildren
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/signin': typeof SigninRoute
  '/survey': typeof SurveyRoute
  '/survey-results': typeof SurveyResultsRoute
  '/admin/basics': typeof AdminBasicsRoute
  '/admin/discount': typeof AdminDiscountRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/theme': typeof AdminThemeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guild/roster': typeof GuildRosterRoute
  '/members_/$slug': typeof MembersSlugRoute
  '/send/$token': typeof SendTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/guild/': typeof GuildIndexRoute
  '/api/admin-media/$assetId': typeof ApiAdminMediaAssetIdRoute
  '/api/confirm-hours/$token': typeof ApiConfirmHoursTokenRoute
  '/api/member-media/$assetId': typeof ApiMemberMediaAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/events'
    | '/guild'
    | '/members'
    | '/news'
    | '/signin'
    | '/survey'
    | '/survey-results'
    | '/admin/basics'
    | '/admin/discount'
    | '/admin/events'
    | '/admin/hours'
    | '/admin/links'
    | '/admin/media'
    | '/admin/theme'
    | '/auth/callback'
    | '/guild/roster'
    | '/members/$slug'
    | '/send/$token'
    | '/admin/'
    | '/guild/'
    | '/api/admin-media/$assetId'
    | '/api/confirm-hours/$token'
    | '/api/member-media/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/members'
    | '/news'
    | '/signin'
    | '/survey'
    | '/survey-results'
    | '/admin/basics'
    | '/admin/discount'
    | '/admin/events'
    | '/admin/hours'
    | '/admin/links'
    | '/admin/media'
    | '/admin/theme'
    | '/auth/callback'
    | '/guild/roster'
    | '/members/$slug'
    | '/send/$token'
    | '/admin'
    | '/guild'
    | '/api/admin-media/$assetId'
    | '/api/confirm-hours/$token'
    | '/api/member-media/$assetId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/events'
    | '/guild'
    | '/members'
    | '/news'
    | '/signin'
    | '/survey'
    | '/survey-results'
    | '/admin/basics'
    | '/admin/discount'
    | '/admin/events'
    | '/admin/hours'
    | '/admin/links'
    | '/admin/media'
    | '/admin/theme'
    | '/auth/callback'
    | '/guild/roster'
    | '/members_/$slug'
    | '/send/$token'
    | '/admin/'
    | '/guild/'
    | '/api/admin-media/$assetId'
    | '/api/confirm-hours/$token'
    | '/api/member-media/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GuildRoute: typeof GuildRouteWithChildren
  MembersRoute: typeof MembersRoute
  NewsRoute: typeof NewsRoute
  SigninRoute: typeof SigninRoute
  SurveyRoute: typeof SurveyRoute
  SurveyResultsRoute: typeof SurveyResultsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MembersSlugRoute: typeof MembersSlugRoute
  SendTokenRoute: typeof SendTokenRoute
  ApiAdminMediaAssetIdRoute: typeof ApiAdminMediaAssetIdRoute
  ApiConfirmHoursTokenRoute: typeof ApiConfirmHoursTokenRoute
  ApiMemberMediaAssetIdRoute: typeof ApiMemberMediaAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survey-results': {
      id: '/survey-results'
      path: '/survey-results'
      fullPath: '/survey-results'
      preLoaderRoute: typeof SurveyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild': {
      id: '/guild'
      path: '/guild'
      fullPath: '/guild'
      preLoaderRoute: typeof GuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild/': {
      id: '/guild/'
      path: '/'
      fullPath: '/guild/'
      preLoaderRoute: typeof GuildIndexRouteImport
      parentRoute: typeof GuildRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/send/$token': {
      id: '/send/$token'
      path: '/send/$token'
      fullPath: '/send/$token'
      preLoaderRoute: typeof SendTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members_/$slug': {
      id: '/members_/$slug'
      path: '/members/$slug'
      fullPath: '/members/$slug'
      preLoaderRoute: typeof MembersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guild/roster': {
      id: '/guild/roster'
      path: '/roster'
      fullPath: '/guild/roster'
      preLoaderRoute: typeof GuildRosterRouteImport
      parentRoute: typeof GuildRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hours': {
      id: '/admin/hours'
      path: '/hours'
      fullPath: '/admin/hours'
      preLoaderRoute: typeof AdminHoursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discount': {
      id: '/admin/discount'
      path: '/discount'
      fullPath: '/admin/discount'
      preLoaderRoute: typeof AdminDiscountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/basics': {
      id: '/admin/basics'
      path: '/basics'
      fullPath: '/admin/basics'
      preLoaderRoute: typeof AdminBasicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/member-media/$assetId': {
      id: '/api/member-media/$assetId'
      path: '/api/member-media/$assetId'
      fullPath: '/api/member-media/$assetId'
      preLoaderRoute: typeof ApiMemberMediaAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/confirm-hours/$token': {
      id: '/api/confirm-hours/$token'
      path: '/api/confirm-hours/$token'
      fullPath: '/api/confirm-hours/$token'
      preLoaderRoute: typeof ApiConfirmHoursTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-media/$assetId': {
      id: '/api/admin-media/$assetId'
      path: '/api/admin-media/$assetId'
      fullPath: '/api/admin-media/$assetId'
      preLoaderRoute: typeof ApiAdminMediaAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBasicsRoute: typeof AdminBasicsRoute
  AdminDiscountRoute: typeof AdminDiscountRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHoursRoute: typeof AdminHoursRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBasicsRoute: AdminBasicsRoute,
  AdminDiscountRoute: AdminDiscountRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHoursRoute: AdminHoursRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GuildRouteChildren {
  GuildRosterRoute: typeof GuildRosterRoute
  GuildIndexRoute: typeof GuildIndexRoute
}

const GuildRouteChildren: GuildRouteChildren = {
  GuildRosterRoute: GuildRosterRoute,
  GuildIndexRoute: GuildIndexRoute,
}

const GuildRouteWithChildren = GuildRoute._addFileChildren(GuildRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GuildRoute: GuildRouteWithChildren,
  MembersRoute: MembersRoute,
  NewsRoute: NewsRoute,
  SigninRoute: SigninRoute,
  SurveyRoute: SurveyRoute,
  SurveyResultsRoute: SurveyResultsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MembersSlugRoute: MembersSlugRoute,
  SendTokenRoute: SendTokenRoute,
  ApiAdminMediaAssetIdRoute: ApiAdminMediaAssetIdRoute,
  ApiConfirmHoursTokenRoute: ApiConfirmHoursTokenRoute,
  ApiMemberMediaAssetIdRoute: ApiMemberMediaAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
